spring:
  application:
    name: service1
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-only
    show-sql: true
server:
  error:
    whitelabel:
      enabled: false
  port: 8081
  ssl:
    key-store: classpath:keytool/keystore.p12
    key-store-password: rootroot
    key-store-type: PKCS12
    key-alias: myserver
    enabled: false
#  servlet:
#    session:
#      cookie:
#        secure: true
#        http-only: true
