spring:
  application:
    name: service1
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s367959
    password: ihU4fUGQ72m1gZIT
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  error:
    whitelabel:
      enabled: false
  port: 8052
  ssl:
    key-store: classpath:helios/keystore.p12
    key-store-password: rootroot
    key-store-type: PKCS12
    key-alias: myserver
    enabled: true
#  servlet:
#    session:
#      cookie:
#        secure: true
#        http-only: true
